language: cpp
sudo: required
dist: trusty

services:
  - docker

branches:
  only:
    - master
    - develop
    - travis # To debug .travis.yml

before_script:
  - docker-compose up --build -d

script:
  - docker exec dcore_container make test

after_script:
  - docker-compose stop
  - docker-compose rm -f

notifications:
  email:
    recipients:
      - dmft-dev@issp.u-tokyo.ac.jp
    on_success: change
    on_failure: always
