version: '3'
services:
  dcoretest:
    build:
      context: .
      dockerfile: Dockerfile-pytest
    tty: true
    working_dir: /var/dcoretest
  examples:
    build:
      context: .
      dockerfile: Dockerfile-examples
    tty: true
    container_name: examples-container
    working_dir: /var/dcoretest
